import { DEFAULT_CONFIG_FILE } from "../config/index.js";
import type { CliOptionDefinition } from "../types/cli.js";

export const OPTION_DEFINITIONS: CliOptionDefinition[] = [
    {
        flags: ["-i", "--input"],
        target: "input",
        takesValue: true,
        valueName: "path",
        required: true,
        description: "Input TS or JS file to bundle and obfuscate.",
    },
    {
        flags: ["-o", "--output"],
        target: "output",
        takesValue: true,
        valueName: "path",
        required: true,
        description: "Output JS file to write.",
    },
    {
        flags: ["-c", "--config"],
        target: "configFile",
        takesValue: true,
        valueName: "path",
        required: false,
        description: `Config JSON file. Defaults to ./${DEFAULT_CONFIG_FILE} when present.`,
    },
    {
        flags: ["--obfuscated-strings", "--obfuscated_strings"],
        helpFlags: ["--obfuscated-strings"],
        target: "obfuscatedStrings",
        takesValue: true,
        valueName: "true|false",
        required: false,
        description: "Enable or disable string literal obfuscation.",
    },
    {
        flags: ["--obfuscated-numbers", "--obfuscated_numbers"],
        helpFlags: ["--obfuscated-numbers"],
        target: "obfuscatedNumbers",
        takesValue: true,
        valueName: "true|false",
        required: false,
        description: "Enable or disable number literal obfuscation.",
    },
    {
        flags: ["--obfuscated-booleans", "--obfuscated_booleans"],
        helpFlags: ["--obfuscated-booleans"],
        target: "obfuscatedBooleans",
        takesValue: true,
        valueName: "true|false",
        required: false,
        description: "Enable or disable boolean literal obfuscation.",
    },
    {
        flags: ["--randomized-unique-identifiers", "--randomized_unique_identifiers"],
        helpFlags: ["--randomized-unique-identifiers"],
        target: "randomizedUniqueIdentifiers",
        takesValue: true,
        valueName: "true|false",
        required: false,
        description: "Use Veyl randomized names instead of esbuild minified identifiers.",
    },
    {
        flags: ["--minify"],
        target: "minify",
        takesValue: true,
        valueName: "true|false",
        required: false,
        description: "Enable or disable the final esbuild minify step.",
    },
    {
        flags: ["--functionify"],
        target: "functionify",
        takesValue: true,
        valueName: "true|false",
        required: false,
        description: "Wrap the transformed program body in a runtime `new Function(...)` call.",
    },
    {
        flags: ["--number-obfuscation-offset", "--number_obfuscation_offset"],
        helpFlags: ["--number-obfuscation-offset"],
        target: "numberObfuscationOffset",
        takesValue: true,
        valueName: "num|randomized",
        required: false,
        description: "Number offset for numeric literal obfuscation.",
    },
    {
        flags: ["--number-obfuscation-operator", "--number_obfuscation_operator"],
        helpFlags: ["--number-obfuscation-operator"],
        target: "numberObfuscationOperator",
        takesValue: true,
        valueName: "+|-|*|/|randomized",
        required: false,
        description: "Number operator for numeric literal obfuscation.",
    },
    {
        flags: ["--boolean-obfuscation-number", "--boolean_obfuscation_number"],
        helpFlags: ["--boolean-obfuscation-number"],
        target: "booleanObfuscationNumber",
        takesValue: true,
        valueName: "num|randomized",
        required: false,
        description: "Numeric token used for obfuscated true values.",
    },
    {
        flags: ["--unnecessary-depth", "--unnecessary_depth"],
        helpFlags: ["--unnecessary-depth"],
        target: "unnecessaryDepth",
        takesValue: true,
        valueName: "true|false",
        required: false,
        description: "Enable or disable unnecessary depth references.",
    },
    {
        flags: ["--log-level", "--log_level"],
        helpFlags: ["--log-level"],
        target: "logLevel",
        takesValue: true,
        valueName: "none|error|info|debug",
        required: false,
        description: "Control CLI output verbosity.",
    },
    {
        flags: ["-h", "--help"],
        target: "help",
        takesValue: false,
        required: false,
        description: "Show this help text.",
    },
    {
        flags: ["-v", "--version"],
        target: "version",
        takesValue: false,
        required: false,
        description: "Show project info, credits, and version.",
    },
];
